/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTolovlarRouteImport } from './routes/_app.tolovlar'
import { Route as AppReytingRouteImport } from './routes/_app.reyting'
import { Route as AppProfilRouteImport } from './routes/_app.profil'
import { Route as AppDokonRouteImport } from './routes/_app.dokon'
import { Route as AppCheckinRouteImport } from './routes/_app.checkin'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppBildirishnomalarRouteImport } from './routes/_app.bildirishnomalar'
import { Route as AppGuruhlarIndexRouteImport } from './routes/_app.guruhlar.index'
import { Route as AppGuruhlarGroupIdRouteImport } from './routes/_app.guruhlar.$groupId'
import { Route as AppDarslarLessonIdRouteImport } from './routes/_app.darslar.$lessonId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTolovlarRoute = AppTolovlarRouteImport.update({
  id: '/tolovlar',
  path: '/tolovlar',
  getParentRoute: () => AppRoute,
} as any)
const AppReytingRoute = AppReytingRouteImport.update({
  id: '/reyting',
  path: '/reyting',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppDokonRoute = AppDokonRouteImport.update({
  id: '/dokon',
  path: '/dokon',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBildirishnomalarRoute = AppBildirishnomalarRouteImport.update({
  id: '/bildirishnomalar',
  path: '/bildirishnomalar',
  getParentRoute: () => AppRoute,
} as any)
const AppGuruhlarIndexRoute = AppGuruhlarIndexRouteImport.update({
  id: '/guruhlar/',
  path: '/guruhlar/',
  getParentRoute: () => AppRoute,
} as any)
const AppGuruhlarGroupIdRoute = AppGuruhlarGroupIdRouteImport.update({
  id: '/guruhlar/$groupId',
  path: '/guruhlar/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppDarslarLessonIdRoute = AppDarslarLessonIdRouteImport.update({
  id: '/darslar/$lessonId',
  path: '/darslar/$lessonId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/bildirishnomalar': typeof AppBildirishnomalarRoute
  '/chat': typeof AppChatRoute
  '/checkin': typeof AppCheckinRoute
  '/dokon': typeof AppDokonRoute
  '/profil': typeof AppProfilRoute
  '/reyting': typeof AppReytingRoute
  '/tolovlar': typeof AppTolovlarRoute
  '/darslar/$lessonId': typeof AppDarslarLessonIdRoute
  '/guruhlar/$groupId': typeof AppGuruhlarGroupIdRoute
  '/guruhlar/': typeof AppGuruhlarIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/bildirishnomalar': typeof AppBildirishnomalarRoute
  '/chat': typeof AppChatRoute
  '/checkin': typeof AppCheckinRoute
  '/dokon': typeof AppDokonRoute
  '/profil': typeof AppProfilRoute
  '/reyting': typeof AppReytingRoute
  '/tolovlar': typeof AppTolovlarRoute
  '/': typeof AppIndexRoute
  '/darslar/$lessonId': typeof AppDarslarLessonIdRoute
  '/guruhlar/$groupId': typeof AppGuruhlarGroupIdRoute
  '/guruhlar': typeof AppGuruhlarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bildirishnomalar': typeof AppBildirishnomalarRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/checkin': typeof AppCheckinRoute
  '/_app/dokon': typeof AppDokonRoute
  '/_app/profil': typeof AppProfilRoute
  '/_app/reyting': typeof AppReytingRoute
  '/_app/tolovlar': typeof AppTolovlarRoute
  '/_app/': typeof AppIndexRoute
  '/_app/darslar/$lessonId': typeof AppDarslarLessonIdRoute
  '/_app/guruhlar/$groupId': typeof AppGuruhlarGroupIdRoute
  '/_app/guruhlar/': typeof AppGuruhlarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bildirishnomalar'
    | '/chat'
    | '/checkin'
    | '/dokon'
    | '/profil'
    | '/reyting'
    | '/tolovlar'
    | '/darslar/$lessonId'
    | '/guruhlar/$groupId'
    | '/guruhlar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/bildirishnomalar'
    | '/chat'
    | '/checkin'
    | '/dokon'
    | '/profil'
    | '/reyting'
    | '/tolovlar'
    | '/'
    | '/darslar/$lessonId'
    | '/guruhlar/$groupId'
    | '/guruhlar'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/bildirishnomalar'
    | '/_app/chat'
    | '/_app/checkin'
    | '/_app/dokon'
    | '/_app/profil'
    | '/_app/reyting'
    | '/_app/tolovlar'
    | '/_app/'
    | '/_app/darslar/$lessonId'
    | '/_app/guruhlar/$groupId'
    | '/_app/guruhlar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tolovlar': {
      id: '/_app/tolovlar'
      path: '/tolovlar'
      fullPath: '/tolovlar'
      preLoaderRoute: typeof AppTolovlarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reyting': {
      id: '/_app/reyting'
      path: '/reyting'
      fullPath: '/reyting'
      preLoaderRoute: typeof AppReytingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dokon': {
      id: '/_app/dokon'
      path: '/dokon'
      fullPath: '/dokon'
      preLoaderRoute: typeof AppDokonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkin': {
      id: '/_app/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bildirishnomalar': {
      id: '/_app/bildirishnomalar'
      path: '/bildirishnomalar'
      fullPath: '/bildirishnomalar'
      preLoaderRoute: typeof AppBildirishnomalarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guruhlar/': {
      id: '/_app/guruhlar/'
      path: '/guruhlar'
      fullPath: '/guruhlar/'
      preLoaderRoute: typeof AppGuruhlarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guruhlar/$groupId': {
      id: '/_app/guruhlar/$groupId'
      path: '/guruhlar/$groupId'
      fullPath: '/guruhlar/$groupId'
      preLoaderRoute: typeof AppGuruhlarGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/darslar/$lessonId': {
      id: '/_app/darslar/$lessonId'
      path: '/darslar/$lessonId'
      fullPath: '/darslar/$lessonId'
      preLoaderRoute: typeof AppDarslarLessonIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBildirishnomalarRoute: typeof AppBildirishnomalarRoute
  AppChatRoute: typeof AppChatRoute
  AppCheckinRoute: typeof AppCheckinRoute
  AppDokonRoute: typeof AppDokonRoute
  AppProfilRoute: typeof AppProfilRoute
  AppReytingRoute: typeof AppReytingRoute
  AppTolovlarRoute: typeof AppTolovlarRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDarslarLessonIdRoute: typeof AppDarslarLessonIdRoute
  AppGuruhlarGroupIdRoute: typeof AppGuruhlarGroupIdRoute
  AppGuruhlarIndexRoute: typeof AppGuruhlarIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBildirishnomalarRoute: AppBildirishnomalarRoute,
  AppChatRoute: AppChatRoute,
  AppCheckinRoute: AppCheckinRoute,
  AppDokonRoute: AppDokonRoute,
  AppProfilRoute: AppProfilRoute,
  AppReytingRoute: AppReytingRoute,
  AppTolovlarRoute: AppTolovlarRoute,
  AppIndexRoute: AppIndexRoute,
  AppDarslarLessonIdRoute: AppDarslarLessonIdRoute,
  AppGuruhlarGroupIdRoute: AppGuruhlarGroupIdRoute,
  AppGuruhlarIndexRoute: AppGuruhlarIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
